server:
  port: 8888

spring:
  application.name: scdemo-gateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
    - id: greeter
      uri: lb://scdemo-greeter
      predicates:
      - Path=/greetings/{name}
      #filters:
      #- SetStatus=202
    - id: pinger
      uri: lb://scdemo-greeter
      predicates:
      - Path=/ping
    - id: talker
      uri: lb://scdemo-talker
      predicates:
      - Path=/just-talk
      #filters:
      #- SetPath=/just-talk

eureka:
  client:
    register-with-eureka: true
    instance:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      leaseRenewalIntervalInSeconds: 5 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

